### ISSUE TITLE
Remove an unnecessary check for an API handle

### ISSUE THREAD

**Issue by elfring** [ucpu/cage#23]
[An extra check is not needed for a zero API handle](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDeleteShader.xhtml "Description from the OpenGL reference") in [the destructor for the class “SourceHolder”](https://github.com/ucpu/cage/blob/ca34da8869b5667316907c31f79c987b4d73d87f/sources/libengine/graphics/shaderProgram.cpp#L46 "Update candidate").

**Comment by malytomas** [comment]
Thanks. The same probably applies to other objects such as textures, buffers, etc. Pull request is welcome.

**Comment by malytomas** [comment]
I suppose such calls were annoying in gpu profiler output. Leaving as is.
