### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by angelskieglazki** [ucpu/cage#31]
Hello, what version of compiler and standard of c++ you use for compile cage on Linux?
```
/home/max/projects/game-engines/cage/sources/libcore/network/ginnel.cpp: In function ‘constexpr cage::FlatSet<short unsigned int> cage::{anonymous}::decodeAck(cage::uint16, cage::uint32)’:
/home/max/projects/game-engines/cage/sources/libcore/network/ginnel.cpp:201:41: error: variable ‘result’ of non-literal type ‘cage::FlatSet<short unsigned int>’ in ‘constexpr’ function
  201 |                         FlatSet<uint16> result
```

I use gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

https://en.cppreference.com/w/cpp/language/constexpr

A constexpr variable must satisfy the following requirements:
it is not of class type nor (possibly multi-dimensional) array thereof, ... (BUT (since C++20))

**Comment by malytomas** [comment]
Cage currently requires g++ >= 12.

It should be available on ubuntu 22:
```bash
sudo apt install g++-12
```

Delete the `build` folder and configure again:
```bash
CC=gcc-12 CXX=g++-12 cmake -DCMAKE_BUILD_TYPE=relwithdebinfo ..
```

**Comment by angelskieglazki** [comment]
> Cage currently requires g++ >= 12.
> 
> It should be available on ubuntu 22:
> 
> ```shell
> sudo apt install g++-12
> ```
> 
> Delete the `build` folder and configure again:
> 
> ```shell
> CC=gcc-12 CXX=g++-12 cmake -DCMAKE_BUILD_TYPE=relwithdebinfo ..
> ```

I just need to switch via "sudo alternatives".
 Thank you :bowtie:
